---
- name: Read sites from services.yml
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../services.yml"
    name: services_data
  delegate_to: localhost
  run_once: true
  become: false

- name: Create site configurations
  ansible.builtin.template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ item.key }}.{{ domain_name }}"
  with_dict: "{{ services_data }}"
  when: item.value.port is defined and item.value.port != ''
  notify: Restart nginx

- name: Remove all files in sites-enabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/
    state: absent

- name: Recreate sites-enabled directory
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/
    state: directory
    mode: "0755"

- name: Enable sites
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item.key }}.{{ domain_name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.{{ domain_name }}"
    state: link
  with_dict: "{{ services_data }}"
  when: item.value.port is defined and item.value.port != ''
  notify: Restart nginx
