---
- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Install OS-dependend packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present

- name: Install vm packages
  ansible.builtin.package:
    name: "{{ vm_packages }}"
    state: present
  when:
    - ansible_facts['virtualization_role'] == 'guest'
    - ansible_facts['virtualization_type'] == 'kvm'
