---
- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Install Ubuntu packages
  ansible.builtin.package:
    name: "{{ ubuntu_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install RHEL packages
  ansible.builtin.package:
    name: "{{ rhel_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install vm packages
  ansible.builtin.package:
    name: "{{ vm_packages }}"
    state: present
  when:
    - ansible_facts['virtualization_role'] == 'guest'
    - ansible_facts['virtualization_type'] == 'kvm'
