---
repos:
  # Formatters first
  - repo: local
    hooks:
      - id: prettier-yaml
        name: Prettier (YAML)
        entry: prettier --write
        language: system
        types: [yaml]
        exclude: ^\.yamllint$
        require_serial: true
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        require_serial: true

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        require_serial: true

  # Linters + whitespace fixers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["ansible", "flake8-pyproject"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_validate
      - id: terraform_tflint

  # Tests last (only run if all previous hooks passed)
  - repo: local
    hooks:
      - id: terraform-tests
        name: Run Terraform tests
        entry: make check/terraform
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: ansible-tests
        name: Run Ansible tests
        entry: make check/ansible
        language: system
        pass_filenames: false
        stages: [pre-commit]
