server:
  friendly_name: Server-old
  ip: 10.10.20.20
  mac: 1e:77:35:5b:1a:a3
  vlan: "20"
  os: ubuntu
server25:
  friendly_name: Server
  ip: 10.10.20.21
  mac: 1e:77:35:5b:1a:bd
  vlan: "20"
  os: ubuntu
home-assistant:
  friendly_name: Home Assistant
  ip: 10.10.10.111
  mac: de:53:8c:82:a2:84
  vlan: "0"
  os: hassos
webserver:
  friendly_name: Webserver
  ip: 10.10.20.10
  mac: aa:d1:84:d5:51:32
  vlan: "20"
  os: ubuntu
production:
  friendly_name: Production
  ip: 10.10.20.242
  mac: bc:24:11:d1:8b:55
  vlan: "20"
  os: ubuntu
plex:
  friendly_name: Plex
  ip: 10.10.20.21
  mac: 8a:83:08:eb:d8:34
  vlan: "20"
  os: ubuntu
rtv:
  friendly_name: RomanTV
  ip: 10.10.20.22
  mac: 02:64:85:72:4b:d5
  vlan: "20"
  os: ubuntu
ansible:
  friendly_name: AAP
  ip: 10.10.20.35
  mac: bc:24:11:4a:98:b6
  vlan: "20"
  os: rhel
proxmox:
  friendly_name: Proxmox
  ip: 10.10.10.250
  mac: 1c:bf:ce:fb:eb:77
  vlan: "0"
  os: debian
unifi:
  friendly_name: UDM Pro
  ip: 10.10.10.1
  mac: 24:5a:4c:72:bf:97
  vlan: "0"
  os: unmanaged
vaultwarden:
  friendly_name: Vaultwarden
  ip: 10.10.10.105
  mac: 0e:84:f0:d1:46:9a
  vlan: "0"
  os: ubuntu
unas:
  friendly_name: UNAS Pro
  ip: 10.10.10.3
  mac: 0c:ea:14:ea:0a:1f
  vlan: "0"
  os: unmanaged
mac-mini:
  friendly_name: Mac Mini
  ip: 10.10.10.10
  mac: 96:6f:18:8d:85:51
  vlan: "0"
  os: macos
nanokvm:
  friendly_name: NanoKVM
  ip: 10.10.20.121
  mac: 48:da:35:6f:49:2e
  vlan: "20"
  os: unmanaged
printer:
  friendly_name: Printer
  ip: 10.10.20.181
  mac: 02:a0:82:3a:1e:23
  vlan: "20"
  os: unmanaged
apple-tv:
  friendly_name: Apple TV 4K
  ip: 10.10.10.8
  mac: 58:d3:49:d4:e5:57
  vlan: "0"
  os: unmanaged
ipad-pro:
  friendly_name: iPad Pro
  ip: 10.10.10.11
  mac: 0a:82:58:28:1f:ce
  vlan: "0"
  os: unmanaged
homepod-mini:
  friendly_name: HomePod Mini
  ip: 10.10.10.206
  mac: 04:99:b9:6e:f5:1d
  vlan: "0"
  os: unmanaged
homepod:
  friendly_name: HomePod
  ip: 10.10.10.209
  mac: d4:a3:3d:66:42:04
  vlan: "0"
  os: unmanaged
symfonisk:
  friendly_name: Symfonisk
  ip: 10.10.11.185
  mac: 34:7e:5c:32:29:62
  vlan: "11"
  os: unmanaged
homewizard:
  friendly_name: HomeWizard
  ip: 10.10.11.230
  mac: 5c:2f:af:19:b3:32
  vlan: "11"
  os: unmanaged
p1s:
  friendly_name: Bambu Lab P1S
  ip: 10.10.11.231
  mac: 3c:84:27:f4:a1:5c
  vlan: "11"
  os: unmanaged
ledstrip:
  friendly_name: Yeelight LED Strip
  ip: 10.10.12.4
  mac: 04:cf:8c:bf:78:e8
  vlan: "12"
  os: unmanaged
slzb-06:
  friendly_name: SLZB-06
  ip: 10.10.12.7
  mac: 78:e3:6d:e3:e3:c3
  vlan: "12"
  os: unmanaged
nrg-itho:
  friendly_name: NRG Itho
  ip: 10.10.12.8
  mac: 2c:bc:bb:15:09:18
  vlan: "12"
  os: unmanaged
vacuum:
  friendly_name: Robot Vacuum
  ip: 10.10.12.215
  mac: c0:e7:bf:7b:f9:e4
  vlan: "12"
  os: unmanaged
