---
services:
  n8n:
    container_name: n8n
    build:
      context: .
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_EDITOR_BASE_URL=https://n8n.${DOMAIN_NAME}
      - WEBHOOK_URL=https://n8n.${DOMAIN_NAME}
    volumes:
      - data:/home/node/.n8n
    restart: unless-stopped

volumes:
  data:
