---
# tasks file for topgrade role

- name: Ensure topgrade is installed
  ansible.builtin.package:
    name: topgrade
    state: present
  when: '"topgrade" in configure'

- name: Ensure config directory exists
  ansible.builtin.file:
    path: >-
      {{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME +
      '/.config') }}
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: "0755"
  when: '"topgrade" in configure'

- name: Deploy topgrade config file
  ansible.builtin.template:
    src: topgrade.toml.j2
    dest: >-
      {{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME +
      '/.config') }}/topgrade.toml
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
  when: '"topgrade" in configure'
