services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Amsterdam/Europe
    #user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ./cache:/var/cache/ntfy
      - ./config:/etc/ntfy
    ports:
      - ${NTFY_PORT}:80
    restart: unless-stopped
