---
- name: Pull Ansible Base
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    fullname: "{{ lookup('pipe', 'getent passwd ' + username + ' | cut -d: -f5 | cut -d, -f1') }}"
    username: "{{ lookup('env', 'USER') }}"

  roles:
    - base
