---
- name: Configure webserver as Nginx reverse proxy
  hosts: webserver
  become: true

  vars:
    # Public domain for external services
    domain_name: romanpeters.nl
    # Local DNS domain for backend hosts and internal services
    dns_domain: local.nl

  roles:
    - webserver