# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="agnoster"

# Auto-update settings
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 90

# Enable command auto-correction.
ENABLE_CORRECTION="false"

# Enable completion waiting dots.
COMPLETION_WAITING_DOTS="true"

# Set history timestamp format.
HIST_STAMPS="dd/mm/yyyy"

# List of plugins to load.
# You may need to install zsh-autosuggestions and zsh-syntax-highlighting separately.
# For example, by cloning them into your $ZSH_CUSTOM/plugins directory.
plugins=(
  gitfast
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Source Oh My Zsh.
source $ZSH/oh-my-zsh.sh

# Custom functions
eval "$(gh copilot alias -- zsh)"
eval "$(zoxide init zsh)"
. "$HOME/.atuin/bin/env"
eval "$(atuin init zsh)"
killport() { kill -9 $(lsof -t -i :$1 -sTCP:LISTEN) }

# Load aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

# nvmd5
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# fetch
echo ''
if (( $+commands[neofetch] )); then
    neofetch
elif (( $+commands[fastfetch] )); then
    fastfetch
fi
