---
- name: Install Tailscale
  become: true
  ansible.builtin.shell:
    cmd: "curl -fsSL https://tailscale.com/install.sh | sh"
  args:
    creates: /usr/bin/tailscale

- name: Use the generated key to register the device
  become: true
  ansible.builtin.command: "tailscale up --auth-key={{ tailscale_authkey }} --operator={{ username }}"
  register: tailscale_up_result
  changed_when: "'Success' in tailscale_up_result.stdout"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Show tailscale status (for verification)
  become: true
  ansible.builtin.command: "tailscale status"
  register: tailscale_status
  changed_when: false
  failed_when:
    - "'stopped' in tailscale_status.stdout"
    - "'Logged out.' in tailscale_status.stdout"
  delay: 5
  retries: 3
