---
- name: Read services from services.yml
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../services.yml"
    name: services_data
  delegate_to: localhost
  run_once: true
  become: false

- name: Get unique docker services for this host
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services | default([]) + [item.value.docker] }}"
  with_dict: "{{ services_data }}"
  when:
    - inventory_hostname == item.value.host
    - item.value.docker is defined
    - item.value.docker != ''
    - item.value.docker != false

- name: Create /srv/docker directory
  become: true
  ansible.builtin.file:
    path: /srv/docker
    state: directory
    owner: root
    group: docker
    mode: "0775"

- name: Place Docker Compose files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../docker/{{ item }}/"
    dest: "/srv/docker/{{ item }}"
    owner: root
    group: docker
  loop: "{{ docker_services | unique }}"

- name: Check for .env files
  ansible.builtin.stat:
    path: "/srv/docker/{{ item }}/.env"
  loop: "{{ docker_services | unique }}"
  register: env_files

- name: Secure .env files
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    mode: "0640"
  loop: "{{ env_files.results }}"
  when: item.stat.exists

- name: Set permissions for docker-compose.yml
  ansible.builtin.file:
    path: "/srv/docker/{{ item }}/docker-compose.yml"
    mode: "0660"
  loop: "{{ docker_services | unique }}"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/srv/docker/{{ item }}"
    state: present
    recreate: always
  loop: "{{ docker_services | unique }}"
