---
- name: Read services from services.yml
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../services.yml"
    name: services_data
  delegate_to: localhost
  run_once: true
  become: false

- name: Initialize docker services var
  ansible.builtin.set_fact:
    docker_services: []

- name: Get unique docker services for this host
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services | default([]) + [service_item.value.docker] }}"
  with_dict: "{{ services_data }}"
  loop_control:
    loop_var: service_item
  when:
    - inventory_hostname == service_item.value.host
    - service_item.value.docker is defined
    - service_item.value.docker != ''
    - service_item.value.docker != false

- name: Create /srv/docker directory
  become: true
  ansible.builtin.file:
    path: /srv/docker
    state: directory
    owner: root
    group: docker
    mode: "0775"

- name: Place Docker Compose files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../docker/{{ service_name }}/"
    dest: "/srv/docker/{{ service_name }}"
    owner: root
    group: docker
    mode: "0660"
    directory_mode: "0775"
    backup: true
  loop: "{{ docker_services | unique }}"
  loop_control:
    loop_var: service_name

- name: Get docker-compose bind mount directories
  script:
    cmd: "{{ role_path }}/files/get_docker_bind_mounts.py"
    chdir: "{{ playbook_dir }}/../.."
  register: bind_mount_dirs
  changed_when: false
  delegate_to: localhost
  run_once: true
  become: false

- name: Ensure directories for docker-compose bind mounts exist
  become: true
  ansible.builtin.file:
    path: "/srv/{{ mount_dir }}"
    state: directory
    owner: root
    group: docker
    mode: "0775"
  loop: "{{ bind_mount_dirs.stdout_lines }}"
  loop_control:
    loop_var: mount_dir
  when: "mount_dir.split('/')[1] in (docker_services | unique)"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/srv/docker/{{ service_name }}"
    state: present
  #    recreate: always
  loop: "{{ docker_services | unique }}"
  loop_control:
    loop_var: service_name
