---
services:
  sonarr:
    image: linuxserver/sonarr:4.0.15.2941-ls292
    container_name: sonarr
    volumes:
      - ./sonarr:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - ${SONARR_PORT}:8989
    restart: always

  radarr:
    image: linuxserver/radarr:5.27.5.10198-ls283
    container_name: radarr
    volumes:
      - ./radarr:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - ${RADARR_PORT}:7878
    restart: always

  bazarr:
    image: linuxserver/bazarr:v1.5.3-ls319
    container_name: bazarr
    volumes:
      - ./bazarr:/config
      - /mnt/media:/media
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - ${BAZARR_PORT}:6767
    restart: always

  readarr:
    image: lscr.io/linuxserver/readarr:develop-0.4.13.2760-ls149
    container_name: readarr
    volumes:
      - ./readarr:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - ${READARR_PORT}:8787
    restart: always

  readarr-audio:
    image: lscr.io/linuxserver/readarr:develop-0.4.13.2760-ls149
    container_name: readarr-audio
    volumes:
      - ./readarr-audio:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - ${READARR_AUDIO_PORT}:8787
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.0.5.5160-ls126
    container_name: prowlarr
    volumes:
      - ./prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - ${PROWLARR_PORT}:9696
    restart: always
