---
# Tasks to deploy NixOS configurations
- name: Check for NixOS configuration file
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ nix_configs_dir }}/{{ inventory_hostname }}.nix"
  register: nix_conf

- name: Skip host without NixOS config
  ansible.builtin.meta: end_host
  when: not nix_conf.stat.exists

- name: Build NixOS configuration for host on control node
  delegate_to: localhost
  ansible.builtin.command: >-
    nix-build {{ inventory_hostname }}.nix -o result-{{ inventory_hostname }}
  args:
    chdir: "{{ nix_configs_dir }}"
  register: nix_build

- name: Copy Nix closure to remote host
  delegate_to: localhost
  ansible.builtin.command: >-
    nix-copy-closure --to {{ inventory_hostname }}
    result-{{ inventory_hostname }}
  args:
    chdir: "{{ nix_configs_dir }}"

- name: Activate NixOS configuration on remote host
  become: true
  ansible.builtin.command: >-
    nixos-rebuild switch --no-build
- name: Clean up local build result
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ nix_configs_dir }}/result-{{ inventory_hostname }}"
    state: absent
